// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEw7_Sd8WufrbG51kvu04ndKVtzVCQrpM',
    appId: '1:837759484127:android:d4b12206d482261f',
    messagingSenderId: '837759484127',
    projectId: 'desi-karaoke',
    databaseURL: 'https://desi-karaoke.firebaseio.com',
    storageBucket: 'desi-karaoke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsLYoOdnZ5Gb_zhjWlDhIzBz-XZXt797w',
    appId: '1:837759484127:ios:165c6f4a5d6aa839b8a96a',
    messagingSenderId: '837759484127',
    projectId: 'desi-karaoke',
    databaseURL: 'https://desi-karaoke.firebaseio.com',
    storageBucket: 'desi-karaoke.appspot.com',
    androidClientId: '837759484127-0r1nmspbek263sia28hhnf2hrh9edhbk.apps.googleusercontent.com',
    iosClientId: '837759484127-13s6a8hn77l11dcpi4d044ft7lclqirc.apps.googleusercontent.com',
    iosBundleId: 'com.desikaraoke.singalong',
  );
}
